# Generated by Django 4.1.6 on 2023-03-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='Doctor')),
                ('hospital_name', models.CharField(max_length=200, null=True)),
                ('specialist', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
