# Generated by Django 4.1.6 on 2023-03-10 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diseaseapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctors',
            new_name='Doctor',
        ),
    ]
